# Generated by Django 4.1.1 on 2022-10-07 13:48

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_names",
                    models.CharField(
                        blank=True,
                        help_text="Enter middle names of the author and separate them with commas, e.g. for J.R.R. Tolkien type 'Ronald, Reuel'.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "date_of_death",
                    models.DateField(blank=True, null=True, verbose_name="Died"),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Main title of the book.", max_length=200
                    ),
                ),
                (
                    "suptitle",
                    models.CharField(
                        blank=True,
                        help_text="Suptitle of a book, leave blank if there is none.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Enter a brief description of the book.",
                        max_length=1000,
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>',
                        max_length=13,
                        unique=True,
                        verbose_name="ISBN",
                    ),
                ),
                ("digital_availability", models.BooleanField(default=False)),
                ("pub_date", models.DateField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="catalog.author",
                    ),
                ),
            ],
            options={
                "ordering": ["title", "-pub_date"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter a book genre (e.g. Science Fiction)",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Enter a brief genre description.", max_length=256
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Nationality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="BookInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique ID for this particular book across whole library.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("due_back", models.DateField(blank=True, null=True)),
                ("imprint", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("m", "Maintenance"),
                            ("o", "On loan"),
                            ("a", "Available"),
                            ("r", "Reserved"),
                        ],
                        default="m",
                        help_text="Book availability",
                        max_length=1,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="catalog.book",
                    ),
                ),
            ],
            options={
                "ordering": ["due_back"],
            },
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(to="catalog.genre"),
        ),
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="catalog.language"
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="nationality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="catalog.nationality"
            ),
        ),
    ]
