# Generated by Django 4.1.1 on 2022-10-07 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="language",
        ),
        migrations.AddField(
            model_name="bookinstance",
            name="language",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                to="catalog.language",
            ),
            preserve_default=False,
        ),
    ]
